model_config:
  input_dim: 3                  # 输入特征数（血压、舒张压、心率）
  pred_length: 60               # 预测步长（原PRED_LENGTH）
  seq_length: 10                # 输入序列长度
  results_dir: "results/model_selection"  # 模型结果保存路径
  ocr_output_path: "data/processed_data"  # OCR输出的标准化数据路径（关键：关联OCR模块）

training_config:
  batch_size: 32
  epochs: 50
  lr_range: [0.0001, 0.01]      # 学习率搜索范围
  hidden_units: [32, 64, 128, 256]  # 隐藏单元候选值
  num_layers_range: [1, 3]      # 网络层数范围

optuna_config:
  n_trials: 50                  # 每个模型的超参数搜索次数
  directions: ["minimize", "minimize", "minimize"]  # 多目标优化方向（MAE、RMSE、1-R²）